#!/usr/bin/env sh

alias ptv="python -m pytest -vv"
alias tsm="transmission-remote"
alias wttr="curl wttr.in/Kyiv"
alias bc="bc -lq"
alias lynx="lynx --display-charset=utf-8"
alias grep="grep --color=always"
alias te='ssh root@test-env.scalr.com -p$1'
alias yt_dmenu='ytfzf -D'

function 0x0 {
    curl -F"f=@$@" https://nptr.kecyk.space/;
}

function brightness {
    xrandr --output `xrandr -q | grep ' connected' | head -n 1 | cut -d ' ' -f1` --brightness $@;
}

function f() {
    find . -name "*$**"
}

