#!/usr/bin/env sh

alias ptv="python -m pytest -vv"
alias wttr="curl wttr.in/Lviv"
alias bc="bc -lq"
alias lynx="lynx --display-charset=utf-8"
alias grep="grep --color=always"
alias k='kubectl'

function 0x0 {
    curl -F"f=@$@" https://nptr.kecyk.io/;
}

function brightness {
    xrandr --output `xrandr -q | grep ' connected' | head -n 1 | cut -d ' ' -f1` --brightness $@;
}

function f() {
    find . -name "*$**"
}

